### ISSUE TITLE
ApplicationEmploymentServiceImpl.findByStatus 함수 Enum

### ISSUE THREAD

**Issue by helpmedev** [chwijunTime/ChwijunTimeServer#94]
![image](https://user-images.githubusercontent.com/24860901/122893547-6396c800-d381-11eb-81c1-753360b6f1d1.png)
74~78라인까지  findByApplicationEmploymentStatus() 함수에 파라미터로 enum을 넣고 있는데 if문에 비교한 enum값과 동일한 값을 넣고있는데, 그냥 status 변수를 넘겨도 될 것 같습니다.

**Comment by ksh030506** [comment]
@helpmedev 
Review 완료하였습니다!
